lifeKart/urls.py
from django.contrib import admin
from django.urls import path,include
from accounts import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.index,name='home'),
    path('accounts/',include('django.contrib.auth.urls')),
    path('signup/',views.SignUp.as_view(),name='signup'),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.
class CustomUser(AbstractUser):
    type = models.CharField(max_length=20,default='')
    name = models.CharField(max_length=40,default='')
    mobile = models.CharField(max_length=12,default='')
    address = models.TextField(max_length=None,default='')
    bloodgroup1 = models.CharField(max_length=4,default='',blank=True)
    bloodgroup2 = models.CharField(max_length=4,default='',blank=True)
    bloodgroup3 = models.CharField(max_length=4,default='',blank=True)
    bloodgroup4 = models.CharField(max_length=4,default='',blank=True)
    bloodgroup5 = models.CharField(max_length=4,default='',blank=True)
    bloodgroup6 = models.CharField(max_length=4,default='',blank=True)
    bloodgroup7 = models.CharField(max_length=4,default='',blank=True)
    bloodgroup8 = models.CharField(max_length=4,default='',blank=True)

    def __str__(self):
        return self.name

accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm,UserChangeForm
from .models import CustomUser


class CustomUserCreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = CustomUser
        fields = ('username','name','type','email','mobile','address','bloodgroup1','bloodgroup2','bloodgroup3','bloodgroup4','bloodgroup5','bloodgroup6','bloodgroup7','bloodgroup8')
    def clean_email(self):
        email = self.cleaned_data.get('email')

        try:
            match = CustomUser.objects.get(email=email)
        except CustomUser.DoesNotExist:
            return email
        raise forms.ValidationError('This Email is Already in Use')
class CustomUserChangeForm(UserChangeForm):
    class Meta:
        model = CustomUser
        fields = ('username','name','type','email','mobile','address','bloodgroup1','bloodgroup2','bloodgroup3','bloodgroup4','bloodgroup5','bloodgroup6','bloodgroup7','bloodgroup8')

accounts/views.py
from django.shortcuts import render
from django.views import generic
from django.urls import reverse_lazy
from accounts.forms import CustomUserCreationForm
# from django.contrib.auth.forms import UserCreationForm
# from django.contrib.auth.decorators import login_required
from .models import CustomUser
from django.db.models import Q


# Create your views here.
def index(request):
    var1 = "none"

    if request.method == 'POST':
        bg = request.POST.get('search')
        var1 = CustomUser.objects.filter(
            Q(bloodgroup1=bg) | Q(bloodgroup2=bg) | Q(bloodgroup3=bg) | Q(bloodgroup4=bg) | Q(bloodgroup5=bg) | Q(
                bloodgroup6=bg) | Q(bloodgroup7=bg) | Q(bloodgroup8=bg))
        return render(request, 'index.html', {'var1': var1, })

    return render(request, 'index.html', {'var1': var1, })


class SignUp(generic.CreateView):
    form_class = CustomUserCreationForm
    success_url = reverse_lazy('login')
    template_name = 'signup.html'

templates/index.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en" dir="ltr">
<head>
    <meta charset="utf-8">
    <title>Life Kart</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static "css/style1.css" %}">
    <link rel="stylesheet" href="{% static "css/sidenav.css" %}">
    <link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
</head>
<body>
<div class="wrapper">
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="/">
            <i class="fa fa-heartbeat" style="font-size:58px;color:red"></i> &nbsp LIFE-KART</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" onclick="openNav()" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon" ></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="/">Home <span class="sr-only">(current)</span></a>
                </li>

                {% if user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'logout' %}">LogOut</a>
                </li>
                {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'login' %}">LogIn</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="signup/">SignUp</a>
                </li>
                {% endif %}
            </ul>
        </div>
    </nav>

    <div id="mySidenav" class="sidenav">
 <a href="javascript:void(0)" class="closebtn" onclick="closeNav()">&times;</a>
 {% if user.is_authenticated %}
  <a href="{% url 'logout' %}">LogOut</a>
  {% else %}
  <a href="{% url 'login' %}">LogIn</a>
 <a href="signup/">SignUp</a>
 {% endif %}
</div>

    <div class="text-center mycls1">
        <h1>How to Use?</h1>
        <h4>You can search any blood group you need.</h4>
    </div>
    <div class="c" style="color:white;">
        <div class="searchbar">
            <form method="post">
                {% csrf_token %}
                <select name="search" required>
                    <option value="" disabled selected="">Select</option>
                    <option value="O+">O+</option>
                    <option value="O-">O-</option>
                    <option value="A+">A+</option>
                    <option value="A-">A-</option>
                    <option value="B+">B+</option>
                    <option value="B-">B-</option>
                    <option value="AB+">AB+</option>
                    <option value="AB-">AB-</option>
                </select>
                <div >
                    <button class="button" type="submit">Search &nbsp <i class="fa fa-search" aria-hidden="true"></i></button>
                </div>
            </form>
        </div>




    </div>
    <center>
        <div id="mytable">
            {% if var1 != 'none' %}

            <table>
                <tr>
                    <th>Name</th>
                    <th>Blood Bank/Donor</th>
                    <th>address</th>
                    <th>mobile</th>
                </tr>
                {% for u in var1 %}

                <tr>
                    <td>{{u.name}}</td>
                    <td>{{u.type}}</td>
                    <td><a href="http://maps.google.com/?q={{u.address}}">{{u.address}}</a></td>
                    <td><a href="tel:{{u.mobile}}">{{u.mobile}}</a></td>
                </tr>





                {% endfor %}</table>{% endif %}</div></center>




</div>
<script type="text/javascript">
  /* Set the width of the side navigation to 250px and the left margin of the page content to 250px and add a black background color to body */
function openNav() {
  document.getElementById("mySidenav").style.width = "250px";
  document.getElementById("main").style.marginLeft = "250px";
  document.body.style.backgroundColor = "rgba(0,0,0,0.4)";
}

/* Set the width of the side navigation to 0 and the left margin of the page content to 0, and the background color of body to white */
function closeNav() {
  document.getElementById("mySidenav").style.width = "0";
  document.getElementById("main").style.marginLeft = "0";
  document.body.style.backgroundColor = "white";
}
</script>
<script>
// Initialize and add the map
function initMap() {
  // The location of Uluru
  var uluru = {lat: 28.629849, lng: 77.372079};
  // The map, centered at Uluru
  var map = new google.maps.Map(
      document.getElementById('map'), {zoom: 17, center: uluru});
  // The marker, positioned at Uluru
  var marker = new google.maps.Marker({position: uluru, map: map});
}
    </script>
<script async defer src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAiX4xuj9WYPegDVaUZDaOBUt_Z0DMf6Ts&callback=initMap"
        type="text/javascript"></script>
</body>
</html>

templates/signup.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
<head>
	<title>Title</title>
</head>
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
	<link rel="stylesheet" href="{% static "css/style2.css" %}">
	<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
<body>
<center>
  <i class="fa fa-heartbeat" style="font-size:58px;color:red"></i>
<div class="logo">
<h1>LIFE KART</h1>
</div></center>
	<div class="wrapper">
		<div class="container">
			<h1>Sign Up</h1>

      <div id="error1">
		{% if form.errors %}
{% for field in form %}
	 {% for error in field.errors %}
			 <div class="alert">
					 <strong>{{ error|escape }}</strong>
			 </div>
	 {% endfor %}
{% endfor %}
{% for error in form.non_field_errors %}
	 <div class="alert">
			 <strong>{{ error|escape }}</strong>
	 </div>
{% endfor %}
{% endif %}
			</div>

			<form class="form" method="post">
        {% csrf_token %}
        <p><label for="id_username">Username:</label> <input class="input" type="text" name="username" maxlength="150" autofocus required id="id_username"> <span class="helptext">Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.</span></p>
<p><label for="id_name">Name:</label> <input class="input" type="text" name="name" maxlength="40" required id="id_name"></p>
<p> <label for="type">Are You a?</label><select class="input" type="text" id="type" name="type" onchange="MyFunction();" required>
					<option value="" disabled selected="">Select</option>
					<option value="Donor">Donor</option>
					<option value="Blood-Bank">Blood-Bank</option>
				</select>
        <p>
          <div id="donor" style="display:none;">
					<select class="blood" name="bloodgroup1">
						<option value="" disabled selected="">Choose Your Blood Group</option>
						<option value="O+">O+</option>
						<option value="O-">O-</option>
						<option value="A+">A+</option>
						<option value="A-">A-</option>
						<option value="B+">B+</option>
						<option value="B-">B-</option>
						<option value="AB+">AB+</option>
						<option value="AB-">AB-</option>
					</select>
				</div>
        </p>
</p>
<p><label for="id_email">Email address:</label> <input class="input" type="email" name="email" maxlength="254" id="id_email"></p>
<p><label for="id_mobile">Mobile:</label> <input class="input" type="text" name="mobile" maxlength="12" required id="id_mobile"></p>
<p><label for="id_address">Address:</label> <input type="text" class="input" name="address" cols="40" rows="10" required id="id_address">
</textarea></p>
<div id="blood-bank" style="display:none;">
          <h3>Blood Groups Available</h3>
					<input class="checkbox" name="bloodgroup1" type="checkbox" value="O+"><label for="bloodgroup1">O+</label>
					<input class="checkbox" name="bloodgroup2" type="checkbox" value="O-"><label for="bloodgroup2">O-</label>
					<input class="checkbox" name="bloodgroup3" type="checkbox" value="A+"><label for="bloodgroup3">A+</label>
					<input class="checkbox" name="bloodgroup4" type="checkbox" value="A-"><label for="bloodgroup4">A-</label>
					<input class="checkbox" name="bloodgroup5" type="checkbox" value="B+"><label for="bloodgroup5">B+</label>
					<input class="checkbox" name="bloodgroup6" type="checkbox" value="B-"><label for="bloodgroup6">B-</label>
					<input class="checkbox" name="bloodgroup7" type="checkbox" value="AB+"><label for="bloodgroup7">AB+</label>
					<input class="checkbox" name="bloodgroup8" type="checkbox" value="AB-"><label for="bloodgroup8">AB-</label>
				</div><p><label for="id_password1">Password:</label> <input class="input" type="password" name="password1" required id="id_password1"> </p>
<p><label for="id_password2"> Re-type Password:</label> <input class="input" type="password" name="password2" required id="id_password2"> </p>

        <button class="mybtn" type="submit" name="button">Sign up</button>
		</div>
	</div>

<script>
	function MyFunction(){
		var1 = document.getElementById("type").value;
		if(var1 == "Donor"){
			document.getElementById("donor").style.display="block";
      document.getElementById("blood-bank").style.display="none";
      document.getElementsByClassName("checkbox").disabled=true;
		}
		else if(var2 = "Blood-Bank"){
		document.getElementById("blood-bank").style.display="block";
    document.getElementById("donor").style.display="none";
    document.getElementsByClassName("blood").disabled=true;

		}
	}
</script>

<script type="text/javascript">
	var password = document.getElementById("id_password1")
  , confirm_password = document.getElementById("id_password2");

function validatePassword(){
  if(password.value != confirm_password.value) {
    confirm_password.setCustomValidity("Passwords Don't Match");
  } else {
    confirm_password.setCustomValidity('');
  }
}

password.onchange = validatePassword;
confirm_password.onkeyup = validatePassword;
</script>

</body>
</html>